version: '3'
services:
  postgres:
    restart: always
    image: sameersbn/postgresql:10-1
    ports:
      - "5432:5432"
    environment:
      - DEBUG=false
      # Infinite loop, to keep it alive, for debugging
      # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
  web:
    volumes:
      - ./app:/app
    ports:
      - "80:80"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
    depends_on:
      - postgres